### ISSUE TITLE
Write a "Getting Started" section on README

### ISSUE THREAD

**Issue by rocktavious** [red-owl-games/Sleipnir#15]

**Comment by sendString** [comment]
This looks really promising! 
A getting started section would be incredible, the demo cs files seem to not quite match the demo in the gif.

**Comment by rocktavious** [comment]
@sendString thanks - Ya i'm working on this in my spare time so i don't get much time.  Its also very very alpha.  When i get it to a more stable "beta-ish" place thats when i'll work on the documentation/readme more.  Keep and eye out! ;)

**Comment by rocktavious** [comment]
Added in 3.0.0
