### ISSUE TITLE
Missing RedOwl.UIEX assembly

### ISSUE THREAD

**Issue by korchoon** [red-owl-games/Sleipnir#19]
Looks like a huge part of repository is missing.
Found it in your another repository red-owl-games/UIEX.
After fixing compile errors (I'm on 19.1) got stuck on missing resource GraphStyles so my graph.

**Comment by rocktavious** [comment]
@korchoon Ya i split out the UIElement framework stuff from the Graph specific stuff to keep a nice separation of concerns.  I'll update the readme and stuff after i get my 2019.1 rewrite finished.

**Comment by rocktavious** [comment]
@korchoon I updated the installation instructions and started a Documenation site using github pages.  https://redowlgames.com/Sleipnir/installation.html
