### ISSUE TITLE
Sample graph compatible with 2019.1

### ISSUE THREAD

**Issue by korchoon** [red-owl-games/Sleipnir#20]
Stuck without working examples. Tried code from README.md, but graph and nodes aren't rendered. Only got top panel: Breadcrumbs and 2 buttons.
Unity 2019.1.0f2

**Comment by rocktavious** [comment]
@korchoon thanks for your interest i'll have a look into this.

**Comment by korchoon** [comment]
Thank you Kyle!

I've forked your repo, branch `19.1` has the case when graph from sample is not rendered in 2019.1.0f2
https://github.com/korchoon/Sleipnir/tree/19.1

**Comment by rocktavious** [comment]
@korchoon I think i've fixed 99% of the bugs with 2019.1 the latest master version of Sleipnir and UIEX.

**Comment by rocktavious** [comment]
I've done some testing and i'm pretty happy with where this is at and am going to start on new features
