### ISSUE TITLE
Cannot import package in Unity 2019.1.4

### ISSUE THREAD

**Issue by FWCorey** [red-owl-games/Sleipnir#38]
When adding to the manifest.json, Unity seems to ignore all of the #if UNITY_EDITOR flags and the package can't be imported
:(

**Comment by rocktavious** [comment]
@FWCorey I can look into this later today - but thats likely because of the assembly definition files.  Maybe there is a misconfiguration there.

**Comment by FWCorey** [comment]
Cheers!

**Comment by rocktavious** [comment]
Hey @FWCorey - I updated the installation instructions - looks like it was a bad naming problem with the UIEX project.  I had
```
"com.redowl.editor.uiex": "https://github.com/red-owl-games/UIEX.git",
```
but it should be
```
"com.redowl.uiex": "https://github.com/red-owl-games/UIEX.git",
```
