### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by FWCorey** [red-owl-games/Sleipnir#39]
When building a project I get this error:
RedOwl\GraphFramework\Engine\Graph\Graph.cs(107,45): error CS0535: 'Graph<T>' does not implement interface member 'IGraph.GetNodesTypes()'

Looking inside there is a #if UNITY_EDITOR wrapping the interface implementation at line #109 in Graph.cs

I'm guessing it's either missing a runtime implementation or the IGraph interface is missing #if UNITY_EDITOR around that part of the interface if it's an editor only method

**Comment by rocktavious** [comment]
@FWCorey Thanks for the report and for using the project - i'll try and take a look at this later tonight or tomorrow.
