### ISSUE TITLE
DemoGraph throws KeyNotFound exception when trying to add nodes

### ISSUE THREAD

**Issue by taylank** [red-owl-games/Sleipnir#40]
Hi,
I tried setting up Sleipnir and playing around with the demo graph, but I'm getting an exception each time I try to add a node:

KeyNotFoundException: The given key was not present in the dictionary.
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <a8ed250850854b439cedc18931a314fe>:0)
RedOwl.GraphFramework.Editor.GraphView.Load (RedOwl.GraphFramework.Graph graph) (at Library/PackageCache/com.redowl.sleipnir@cb5037f60795cb2ad36ed5125cd14c64b4165f8e/RedOwl/GraphFramework/Editor/GraphView.cs:100)
RedOwl.GraphFramework.Editor.GraphWindow.LoadGraph (RedOwl.GraphFramework.Graph graph) (at Library/PackageCache/com.redowl.sleipnir@cb5037f60795cb2ad36ed5125cd14c64b4165f8e/RedOwl/GraphFramework/Editor/GraphWindow.cs:83)
RedOwl.GraphFramework.Editor.GraphEditor.OnGUI () (at Library/PackageCache/com.redowl.sleipnir@cb5037f60795cb2ad36ed5125cd14c64b4165f8e/RedOwl/GraphFramework/Editor/GraphEditor.cs:18)
RedOwl.Editor.RedOwlEditor`1[T].OnInspectorGUI () (at Library/PackageCache/com.redowl.uiex@0268937050cd136d2dabf5b6ea8d2c2a70f06b6b/RedOwl/UIEX/RedOwlEditor.cs:18)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass53_0.<CreateIMGUIInspectorFromEditor>b__0 () (at <f68ca06da1c243afa30519f1c09ba13a>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by SirPolly** [comment]
p.s. I just added a try&catch around the offending line.
